import type { User } from "@/types";

const userData: User = {
    email: "jane.doe@example.com",
    created_at: "2024-01-01",
    staked_amount: 1000,
    uid: "1234567890",
    username: "Jane Doe",
    avatar: "https://github.com/shadcn.png",
    
    habitContracts: [
      { 
        contractId: "1",
        userId: "1234567890",
        habitId: 1,
        startDate: new Date().toISOString(),
        endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        lastVerifiedDate: new Date().toISOString(),
        habitVerifier: "self",
        username: "Jane Doe",
        title: "Daily Exercise",
        subtitle: "30 minutes of cardio",
        progress: { streak: 7, days: {} },
        duration: 30,
        stakedAmount: 50,
        freePassesAllowed: 2,
        totalStakers: 1500,
        status: 'Active',
        dailyCheckin: false,
        usedPasses: 0,
        createdAt: new Date().toISOString(),
      },
      { 
        contractId: "2",
        userId: "1234567890",
        habitId: 2,
        startDate: new Date().toISOString(),
        endDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
        lastVerifiedDate: new Date().toISOString(),
        habitVerifier: "self",
        username: "Jane Doe",
        title: "Meditation",
        subtitle: "15 minutes of mindfulness",
        progress: { streak: 15, days: {} },
        duration: 21,
        stakedAmount: 100,
        freePassesAllowed: 1,
        totalStakers: 2000,
        status: 'Active',
        dailyCheckin: true,
        usedPasses: 0,
        createdAt: new Date().toISOString(),
      },
      { 
        contractId: "3",
        userId: "1234567890",
        habitId: 3,
        startDate: new Date().toISOString(),
        endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
        lastVerifiedDate: new Date().toISOString(),
        habitVerifier: "self",
        username: "Jane Doe",
        title: "Reading",
        subtitle: "Read 20 pages",
        progress: { streak: 5, days: {} },
        duration: 14,
        stakedAmount: 30,
        freePassesAllowed: 3,
        totalStakers: 1000,
        status: 'Failed',
        dailyCheckin: false,
        usedPasses: 0,
        createdAt: new Date().toISOString(),
      },
      { 
        contractId: "4",
        userId: "1234567890",
        habitId: 4,
        startDate: new Date().toISOString(),
        endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        lastVerifiedDate: new Date().toISOString(),
        habitVerifier: "self",
        username: "Jane Doe",
        title: "Healthy Eating",
        subtitle: "No junk food",
        progress: { streak: 10, days: {} },
        duration: 30,
        stakedAmount: 75,
        freePassesAllowed: 0,
        totalStakers: 1800,
        status: 'Completed',
        dailyCheckin: true,
        usedPasses: 0,
        createdAt: new Date().toISOString(),
      }
    ]
  }

export default userData;